# Generated by Django 5.1 on 2024-08-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reportstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstatus',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
